import SessionWrapper from './components/SessionWrapper';
import { Inter } from "next/font/google";
import MainHeader from '@/app/components/main-header/main-header';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <MainHeader />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
